name: Build

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build:
    name: Build and deploy JS bundle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up docusaurus cache
      uses: actions/cache@v3
      with:
        path: doc-site/.yarn/.cache/webpack
        key: ${{ runner.os }}-doc-site-docusaurus-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-doc-site-docusaurus-${{ github.ref }}
          ${{ runner.os }}-doc-site-docusaurus-
    - name: Install libvips42
      run: sudo apt-get update && sudo apt-get install libvips42
    - name: install node
      uses: actions/setup-node@v3
      with:
        cache: yarn
    - name: yarn install
      run: yarn install
    - name: Build bundle
      run: yarn run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/static
